// Bilingual content dictionary for ModuleXVB Decor one-page site
window.SR = {
  nav: { home: "Početna", about: "O nama", collection: "Kolekcija", inspiration: "Inspiracija", services: "Usluge", contact: "Kontakt" },
  hero: {
    eyebrow: "Premium plants & event decor",
    titleTop: "Luksuzna",
    titleScript: "Mediteranska Kolekcija Bilja",
    sub: "Kurirana selekcija maslina, palmi i egzotičnog bilja za hotele, vile, restorane i nezaboravne događaje.",
    ctaPrimary: "Kontaktirajte nas",
    ctaSecondary: "Pogledajte kolekciju",
  },
  about: {
    kicker: "O nama",
    title: "O nama",
    p1: "Modulex je mlada firma sa jasnom vizijom: da unese eleganciju mediterana u svaki prostor.",
    p2: "Specijalizovani smo za najkvalitetnije masline, palme i egzotične biljke koje transformišu hotele, vile, restorane, događaje i privatne prostore u jedinstvena mesta.",
    highlight: "Mlada firma. Velika strast. Beskompromisan kvalitet.",
    stats: [
      { num: "100%", label: "Uvozne, provjerene sadnice", showNum: true },
      { num: "20+", label: "Vrsta u ponudi", showNum: true },
      { num: "", label: "Odabrana kolekcija", icon: true, showNum: false },
    ],
  },
  benefits: [
    { title: "Pažljivo birano", text: "Svaki primerak lično pregledamo pre isporuke.", icon: "leaf" },
    { title: "Vrhunski kvalitet", text: "Samo zreli, formirani primerci ulaze u kolekciju.", icon: "gem" },
    { title: "Zdrave i jake biljke", text: "Aklimatizovane i spremne da odmah uspevaju.", icon: "sprout" },
    { title: "Posvećeni vama", text: "Savet i podrška od izbora do postavljanja.", icon: "handshake" },
  ],
  why: {
    title: "Zašto Modulex?",
    items: [
      { num: "01", text: "Direktan uvoz i pažljivo odabrani primerci" },
      { num: "02", text: "Profesionalno održavanje i nega" },
      { num: "03", text: "Fleksibilna rešenja za svaki prostor" },
      { num: "04", text: "Lično angažovan tim i podrška" },
    ],
  },
  collectionKicker: "Kolekcija",
  collectionTitle: "Naša premium selekcija",
  priceLabel: "Cena na upit",
  sections: {
    olives: {
      num: "01",
      title: "Mediteranske masline",
      text: "Unikatne, stare mediteranske masline koje donose karakter, istoriju i eleganciju.",
      bullets: ["Prirodno formirane krošnje", "Stare i debele stabljike", "Idealne za luksuzne prostore", "Dostupne u više veličina"],
      image: "assets/olive-main.jpg",
    },
    oldOlives: {
      num: "02",
      title: "Stare mediteranske masline",
      text: "Pažljivo birani primerci maslina sa debelim deblom i impresivnim krunama.",
      items: [
        { name: "Maslina S", image: "assets/olive-old-m.jpg" },
        { name: "Maslina M", image: "assets/olive-old-s.jpg" },
        { name: "Maslina L", image: "assets/olive-old-l.jpg" },
        { name: "Maslina XL", image: "assets/olive-old-xl.jpg" },
      ],
    },
    exotic: {
      num: "03",
      title: "Juke, cikasi i egzotične biljke",
      text: "Egzotične biljke koje unose strukturu, stil i tropsku atmosferu u svaki ambijent.",
      bullets: ["Otporne i dugotrajne", "Idealne za spoljašnje i unutrašnje prostore", "Dostupne u više veličina"],
      items: [
        { name: "Yucca Rostrata", image: "assets/yucca-rostrata.jpg" },
        { name: "Cycas Revoluta", image: "assets/cycas-revoluta.jpg" },
        { name: "Agave Americana", image: "assets/agave-americana.jpg" },
        { name: "Dracena Draco", image: "assets/dracena-draco.jpg" },
      ],
    },
    palms: {
      num: "04",
      title: "Velike mediteranske palme",
      text: "Impozantne palme koje stvaraju sofisticiranu, luksuznu i prepoznatljivu atmosferu.",
      items: [
        { name: "Washingtonia", image: "assets/palm-washingtonia.jpg" },
        { name: "Phoenix canariensis", image: "assets/palm-phoenix-canariensis.jpg" },
        { name: "Phoenix dactylifera", image: "assets/palm-phoenix-dactylifera.jpg" },
        { name: "Chamaerops humilis", image: "assets/palm-chamaerops-humilis.jpg" },
        { name: "Trachycarpus fortunei", image: "assets/palm-trachycarpus-fortunei.jpg" },
      ],
    },
    rental: {
      num: "05",
      title: "Rental premium kolekcija",
      text: "Fleksibilna ponuda za sve vrste događaja, festivale, venčanja, korporativne i privatne proslave.",
      cards: [
        { title: "Male masline, cikasi, juke i palme", image: "assets/cycas-revoluta.jpg" },
        { title: "Velike palme", image: "assets/palm-washingtonia.jpg" },
        { title: "Stare masline (premium primerci)", image: "assets/olive-old-xl.jpg" },
      ],
    },
  },
  inspiration: {
    kicker: "Inspiracija",
    title: "Inspiracija za vaše događaje",
    items: [
      { name: "Venčanja", image: "assets/inspiration-wedding.jpg" },
      { name: "Festivali", image: "assets/inspiration-festival.jpg" },
      { name: "Hoteli", image: "assets/inspiration-hotel.jpg" },
      { name: "Restorani", image: "assets/inspiration-restaurant.jpg" },
      { name: "VIP događaji", image: "assets/inspiration-vip.jpg" },
      { name: "Privatne proslave", image: "assets/inspiration-private.jpg" },
      { name: "Terase", image: "assets/inspiration-terrace.jpg" },
      { name: "Bašte", image: "assets/inspiration-garden.jpg" },
      { name: "Luksuzne vile", image: "assets/inspiration-villa.jpg" },
      { name: "Korporativni eventi", image: "assets/inspiration-corporate.jpg" },
      { name: "Beach barovi", image: "assets/inspiration-beachbar.jpg" },
      { name: "Spa / wellness prostori", image: "assets/inspiration-spa.jpg" },
    ],
  },
  service: {
    kicker: "Usluge",
    title: "Naša kompletna usluga",
    sub: "Od konsultacija do realizacije – mi brinemo o svakom detalju.",
    steps: [
      { title: "Konsultacije i planiranje", icon: "clipboard" },
      { title: "Transport i dostava", icon: "truck" },
      { title: "Instalacija i pozicioniranje", icon: "crane" },
      { title: "Održavanje i nega", icon: "sprout" },
      { title: "Demontaža i odvoz", icon: "box" },
    ],
  },
  contact: {
    kicker: "Kontakt",
    title: "Stupite u kontakt",
    sub: "Recite nam o svom prostoru i događaju — pripremićemo predlog kolekcije za vas.",
    location: "Novi Sad, Srbija",
    ctaCall: "Pozovite nas",
    ctaEmail: "Pošaljite email",
  },
  footer: {
    tagline: "Premium plants & event decor",
    rights: "Sva prava zadržana.",
  },
};

window.EN = {
  nav: { home: "Home", about: "About", collection: "Collection", inspiration: "Inspiration", services: "Services", contact: "Contact" },
  hero: {
    eyebrow: "Premium plants & event decor",
    titleTop: "Luxury",
    titleScript: "Mediterranean Plant Collection",
    sub: "A curated selection of olive trees, palms and exotic plants for hotels, villas, restaurants and unforgettable events.",
    ctaPrimary: "Contact us",
    ctaSecondary: "View collection",
  },
  about: {
    kicker: "About us",
    title: "About us",
    p1: "Modulex is a young company with a clear vision: to bring Mediterranean elegance into every space.",
    p2: "We specialize in premium olives, palms, and exotic plants that transform hotels, villas, restaurants, events, and private spaces into unique places.",
    highlight: "A young company. Great passion. Uncompromising quality.",
    stats: [
      { num: "100%", label: "Imported, inspected specimens", showNum: true },
      { num: "20+", label: "Varieties offered", showNum: true },
      { num: "", label: "Curated collection", icon: true, showNum: false },
    ],
  },
  benefits: [
    { title: "Carefully selected", text: "Every specimen is personally inspected before delivery.", icon: "leaf" },
    { title: "Premium quality", text: "Only mature, well-formed specimens make the collection.", icon: "gem" },
    { title: "Healthy, strong plants", text: "Acclimatized and ready to thrive from day one.", icon: "sprout" },
    { title: "Dedicated to you", text: "Guidance and support from selection to placement.", icon: "handshake" },
  ],
  why: {
    title: "Why Modulex?",
    items: [
      { num: "01", text: "Direct import and carefully selected specimens" },
      { num: "02", text: "Professional maintenance and care" },
      { num: "03", text: "Flexible solutions for every space" },
      { num: "04", text: "Personally engaged team and support" },
    ],
  },
  collectionKicker: "Collection",
  collectionTitle: "Our premium selection",
  priceLabel: "Price on request",
  sections: {
    olives: {
      num: "01",
      title: "Mediterranean Olive Trees",
      text: "Unique old Mediterranean olive trees that bring character, history, and elegance.",
      bullets: ["Naturally shaped crowns", "Old and thick trunks", "Ideal for luxury spaces", "Available in multiple sizes"],
      image: "assets/olive-main.jpg",
    },
    oldOlives: {
      num: "02",
      title: "Old Mediterranean Olive Trees",
      text: "Carefully selected olive specimens with thick trunks and impressive crowns.",
      items: [
        { name: "Olive S", image: "assets/olive-old-m.jpg" },
        { name: "Olive M", image: "assets/olive-old-s.jpg" },
        { name: "Olive L", image: "assets/olive-old-l.jpg" },
        { name: "Olive XL", image: "assets/olive-old-xl.jpg" },
      ],
    },
    exotic: {
      num: "03",
      title: "Yucca, Cycas and Exotic Plants",
      text: "Exotic plants that bring structure, style, and a tropical atmosphere to every setting.",
      bullets: ["Durable and long-lasting", "Ideal for indoor and outdoor spaces", "Available in multiple sizes"],
      items: [
        { name: "Yucca Rostrata", image: "assets/yucca-rostrata.jpg" },
        { name: "Cycas Revoluta", image: "assets/cycas-revoluta.jpg" },
        { name: "Agave Americana", image: "assets/agave-americana.jpg" },
        { name: "Dracena Draco", image: "assets/dracena-draco.jpg" },
      ],
    },
    palms: {
      num: "04",
      title: "Large Mediterranean Palms",
      text: "Impressive palms that create a sophisticated, luxurious, and recognizable atmosphere.",
      items: [
        { name: "Washingtonia", image: "assets/palm-washingtonia.jpg" },
        { name: "Phoenix canariensis", image: "assets/palm-phoenix-canariensis.jpg" },
        { name: "Phoenix dactylifera", image: "assets/palm-phoenix-dactylifera.jpg" },
        { name: "Chamaerops humilis", image: "assets/palm-chamaerops-humilis.jpg" },
        { name: "Trachycarpus fortunei", image: "assets/palm-trachycarpus-fortunei.jpg" },
      ],
    },
    rental: {
      num: "05",
      title: "Premium Rental Collection",
      text: "Flexible offer for all types of events, festivals, weddings, corporate and private celebrations.",
      cards: [
        { title: "Small olives, cycads, yuccas and palms", image: "assets/cycas-revoluta.jpg" },
        { title: "Large palms", image: "assets/palm-washingtonia.jpg" },
        { title: "Old olive trees (premium specimens)", image: "assets/olive-old-xl.jpg" },
      ],
    },
  },
  inspiration: {
    kicker: "Inspiration",
    title: "Inspiration for your events",
    items: [
      { name: "Weddings", image: "assets/inspiration-wedding.jpg" },
      { name: "Festivals", image: "assets/inspiration-festival.jpg" },
      { name: "Hotels", image: "assets/inspiration-hotel.jpg" },
      { name: "Restaurants", image: "assets/inspiration-restaurant.jpg" },
      { name: "VIP events", image: "assets/inspiration-vip.jpg" },
      { name: "Private celebrations", image: "assets/inspiration-private.jpg" },
      { name: "Terraces", image: "assets/inspiration-terrace.jpg" },
      { name: "Gardens", image: "assets/inspiration-garden.jpg" },
      { name: "Luxury villas", image: "assets/inspiration-villa.jpg" },
      { name: "Corporate events", image: "assets/inspiration-corporate.jpg" },
      { name: "Beach bars", image: "assets/inspiration-beachbar.jpg" },
      { name: "Spa / wellness spaces", image: "assets/inspiration-spa.jpg" },
    ],
  },
  service: {
    kicker: "Services",
    title: "Our complete service",
    sub: "From consultation to realization – we take care of every detail.",
    steps: [
      { title: "Consultation and planning", icon: "clipboard" },
      { title: "Transport and delivery", icon: "truck" },
      { title: "Installation and positioning", icon: "crane" },
      { title: "Maintenance and care", icon: "sprout" },
      { title: "Dismantling and removal", icon: "box" },
    ],
  },
  contact: {
    kicker: "Contact",
    title: "Get in touch",
    sub: "Tell us about your space and event — we'll prepare a collection proposal for you.",
    location: "Novi Sad, Serbia",
    ctaCall: "Call us",
    ctaEmail: "Send an email",
  },
  footer: {
    tagline: "Premium plants & event decor",
    rights: "All rights reserved.",
  },
};
